import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
       <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      
      <body className="font-sans antialiased">
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
